env:
  es2021: true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  extraFileExtensions: ['.mjs']
  project: ./tsconfig.json
  sourceType: module
overrides:
  - files: ['*.mjs']
    rules:
      import/extensions: [error, always]
      no-console: off
      '@typescript-eslint/explicit-module-boundary-types': off
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/no-unsafe-assignment': off
      '@typescript-eslint/no-unsafe-member-access': off
      '@typescript-eslint/no-unsafe-call': off
      '@typescript-eslint/no-unsafe-return': off
      '@typescript-eslint/restrict-template-expressions': off
root: true
ignorePatterns: [build]
rules:
  class-methods-use-this:
    [error, {exceptMethods: [getOrigin, getMethod, onResponse, willNavigateTo]}]
  import/order:
    - error
    - alphabetize: {order: asc}
      groups:
        - builtin
        - external
        - internal
        - unknown
        - parent
        - sibling
        - index
        - object
        - type
      newlines-between: always
      warnOnUnassignedImports: true
  import/extensions: [error, never]
  no-await-in-loop: off
  no-restricted-syntax: off
  import/prefer-default-export: off
settings:
  import/extensions: [.mjs, .ts]
  import/resolver:
    node:
      extensions: [.mjs, .ts]
