env:
  es2021: true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  sourceType: module
plugins: [simple-import-sort]
root: true
ignorePatterns: [bin/TestCafeFork/package, build]
rules:
  class-methods-use-this:
    - error
    - {exceptMethods: [getOrigin, getMethod, getParamsFromUrl, getPath, willNavigateTo]}
  curly: [error, all]
  default-param-last: off
  import/exports-last: error
  import/extensions: [error, never]
  import/named: error
  import/no-commonjs: error
  import/no-default-export: error
  import/no-deprecated: error
  import/no-duplicates: error
  import/no-internal-modules:
    - error
    - allow:
        - '**/actions/*'
        - '**/constants/internal'
        - '**/context/*'
        - '**/e2ed/*/*'
        - '**/types/internal'
        - '**/utils/*'
  import/no-unassigned-import: error
  import/no-unused-modules:
    - error
    - ignoreExports: [src/package/context, src/package/index.ts]
      missingExports: false
      unusedExports: true
  import/order: off
  import/prefer-default-export: off
  import/unambiguous: error
  no-await-in-loop: off
  no-continue: off
  no-restricted-syntax: off
  no-shadow: off
  no-useless-constructor: off
  no-use-before-define: off
  no-void: off
  padding-line-between-statements:
    - error
    - {blankLine: always, prev: class, next: '*'}
    - {blankLine: always, prev: '*', next: class}
    - {blankLine: always, prev: [const, let], next: '*'}
    - {blankLine: always, prev: '*', next: [const, let]}
    - {blankLine: any, prev: [const, let], next: [const, let]}
    - {blankLine: always, prev: for, next: '*'}
    - {blankLine: always, prev: '*', next: for}
    - {blankLine: always, prev: '*', next: return}
    - {blankLine: always, prev: try, next: '*'}
    - {blankLine: always, prev: '*', next: try}
  simple-import-sort/exports: error
  simple-import-sort/imports:
    - error
    - groups:
        - ['^(child_process|crypto|fs|http|https|path|querystring|stream|url|util)(/.*|$)']
        - ['^\w']
        - ['^\u0000']
        - ['^\.\./\.\./\.\./\.\.(?!/?$)', '^\.\./\.\./\.\./\.\./?$']
        - ['^\.\./\.\./\.\.(?!/?$)', '^\.\./\.\./\.\./?$']
        - ['^\.\./\.\.(?!/?$)', '^\.\./\.\./?$']
        - ['^\.\.(?!/?$)', '^\.\./?$']
        - ['^\./(?=.*/)(?!/?$)', '^\.(?!/?$)', '^\./?$']
        - ['^\w.*\u0000$']
        - ['^[^.].*\u0000$']
        - ['^\.\./\.\./\.\./\.\./.*\u0000$']
        - ['^\.\./\.\./\.\./.*\u0000$']
        - ['^\.\./\.\./.*\u0000$']
        - ['^\.\./.*\u0000$']
        - ['^\..*\u0000$']
  sort-keys: [error, asc, {caseSensitive: true, natural: false}]
  '@typescript-eslint/default-param-last': [error]
  '@typescript-eslint/explicit-function-return-type': [error, {allowExpressions: true}]
  '@typescript-eslint/explicit-member-accessibility': [error, {accessibility: no-public}]
  '@typescript-eslint/no-namespace': [error, {allowDeclarations: true}]
  '@typescript-eslint/no-shadow': [error]
  '@typescript-eslint/no-use-before-define': [error]
  '@typescript-eslint/quotes': [error, single, {avoidEscape: true}]
settings:
  import/extensions: [.ts]
  import/resolver: {node: {extensions: [.ts]}}
