env:
  es2021: true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  sourceType: module
root: true
ignorePatterns: [build]
rules:
  class-methods-use-this:
    [error, {exceptMethods: [getOrigin, getMethod, getPath, onResponse, willNavigateTo]}]
  import/order:
    - error
    - alphabetize: {order: asc}
      groups:
        - builtin
        - external
        - internal
        - unknown
        - parent
        - sibling
        - index
        - object
        - type
      newlines-between: always
      warnOnUnassignedImports: true
  import/extensions: [error, never]
  no-await-in-loop: off
  no-restricted-syntax: off
  import/prefer-default-export: off
  '@typescript-eslint/no-namespace': [error, {allowDeclarations: true}]
settings:
  import/extensions: [.ts]
  import/resolver:
    node:
      extensions: [.ts]
