env:
  es2021: true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  sourceType: module
root: true
ignorePatterns: [bin, build]
rules:
  class-methods-use-this:
    - error
    - {exceptMethods: [getOrigin, getMethod, getPath, onResponse, searchString, willNavigateTo]}
  curly: [error, all]
  default-param-last: off
  import/extensions: [error, never]
  import/no-default-export: error
  import/order:
    - error
    - alphabetize: {order: asc}
      groups:
        - builtin
        - external
        - internal
        - unknown
        - parent
        - sibling
        - index
        - object
        - type
      newlines-between: always
      warnOnUnassignedImports: true
  import/prefer-default-export: off
  no-await-in-loop: off
  no-restricted-syntax: off
  no-useless-constructor: off
  no-use-before-define: off
  no-void: off
  padding-line-between-statements:
    - error
    - {blankLine: always, prev: class, next: '*'}
    - {blankLine: always, prev: '*', next: class}
    - {blankLine: always, prev: [const, let], next: '*'}
    - {blankLine: always, prev: '*', next: [const, let]}
    - {blankLine: any, prev: [const, let], next: [const, let]}
    - {blankLine: always, prev: for, next: '*'}
    - {blankLine: always, prev: '*', next: for}
    - {blankLine: always, prev: '*', next: return}
    - {blankLine: always, prev: try, next: '*'}
    - {blankLine: always, prev: '*', next: try}
  '@typescript-eslint/default-param-last': [error]
  '@typescript-eslint/explicit-function-return-type': [error, {allowExpressions: true}]
  '@typescript-eslint/explicit-member-accessibility': [error, {accessibility: no-public}]
  '@typescript-eslint/no-namespace': [error, {allowDeclarations: true}]
  '@typescript-eslint/no-use-before-define': [error]
overrides:
  - files: ['**/bin/**/*.ts']
    rules:
      no-console: off
settings:
  import/extensions: [.ts]
  import/resolver:
    node:
      extensions: [.ts]
