name: ci

on: push

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 22.14.0
      - run: npm ci
      - run: npm run build
      - run: npm run build:docker

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 22.14.0
      - run: npm ci
      - run: npm run build
      - run: npm run lint

  test-local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 22.14.0
      - run: npm ci
      - run: npm run build
      - run: npm run test:local
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: reports
          path: build/autotests/reports
